# Generated by Django 5.2.6 on 2025-09-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainreceipt',
            name='hash_value',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
