# Generated by Django 5.2.6 on 2025-09-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_blockchainreceipt_hash_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchainreceipt',
            options={'verbose_name': 'Blockchain Receipt', 'verbose_name_plural': 'Blockchain Receipts'},
        ),
        migrations.AddField(
            model_name='blockchainreceipt',
            name='block_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
