# Generated by Django 5.2.8 on 2025-11-16 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_blockchainreceipt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'Content cannot be empty')]),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1, 'Title cannot be empty')]),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_at'], name='notes_note_created_067654_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['title'], name='notes_note_title_876fe7_idx'),
        ),
    ]
